### ISSUE TITLE
Hi, there is a bug in main.py?

### ISSUE THREAD

**Issue by lovechang1986** [pornpra/YOLOv8-and-DeepSORT-with-TensorRT-#1]
When I run the main.py file, this error ocured:
```
abcdtest@ubuntu:~/YOLOv8-and-DeepSORT-with-TensorRT$ python3 main.py 
OpenCV: FFMPEG: tag 0x34504d46/'FMP4' is not supported with codec id 12 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x7634706d/'mp4v'
Traceback (most recent call last):
  File "main.py", line 28, in <module>
    results = object_detection.predict(source, stream=True, device=device, classes=classes, verbose=False, stream_buffer=True)
NameError: name 'classes' is not defined
```
Would you help me to solve?

**Comment by 1204Gin** [comment]
> When I run the main.py file, this error ocured:
> 
> ```
> abcdtest@ubuntu:~/YOLOv8-and-DeepSORT-with-TensorRT$ python3 main.py 
> OpenCV: FFMPEG: tag 0x34504d46/'FMP4' is not supported with codec id 12 and format 'mp4 / MP4 (MPEG-4 Part 14)'
> OpenCV: FFMPEG: fallback to use tag 0x7634706d/'mp4v'
> Traceback (most recent call last):
>   File "main.py", line 28, in <module>
>     results = object_detection.predict(source, stream=True, device=device, classes=classes, verbose=False, stream_buffer=True)
> NameError: name 'classes' is not defined
> ```
> 
> Would you help me to solve?
你好，请问你的问题解决了吗？Traceback (most recent call last):
  File "main.py", line 28, in <module>
    results = object_detection.predict(source, stream=True, device=device, classes=0, verbose=False, stream_buffer=True)
  File "/home/nvidia/.local/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/nvidia/.local/lib/python3.8/site-packages/ultralytics/yolo/engine/model.py", line 249, in predict
    self.predictor = TASK_MAP[self.task][3](overrides=overrides, _callbacks=self.callbacks)
  File "/home/nvidia/.local/lib/python3.8/site-packages/ultralytics/yolo/engine/predictor.py", line 86, in __init__
    self.args = get_cfg(cfg, overrides)
  File "/home/nvidia/.local/lib/python3.8/site-packages/ultralytics/yolo/cfg/__init__.py", line 112, in get_cfg
    check_cfg_mismatch(cfg, overrides)
  File "/home/nvidia/.local/lib/python3.8/site-packages/ultralytics/yolo/cfg/__init__.py", line 185, in check_cfg_mismatch
    raise SyntaxError(string + CLI_HELP_MSG) from e
SyntaxError: 'stream_buffer' is not a valid YOLO argument. 

    Arguments received: ['yolo']. Ultralytics 'yolo' commands use the following syntax:

        yolo TASK MODE ARGS

        Where   TASK (optional) is one of ('detect', 'segment', 'classify', 'pose')
                MODE (required) is one of ('train', 'val', 'predict', 'export', 'track', 'benchmark')
                ARGS (optional) are any number of custom 'arg=value' pairs like 'imgsz=320' that override defaults.
                    See all ARGS at https://docs.ultralytics.com/usage/cfg or with 'yolo cfg'

    1. Train a detection model for 10 epochs with an initial learning_rate of 0.01
        yolo train data=coco128.yaml model=yolov8n.pt epochs=10 lr0=0.01

    2. Predict a YouTube video using a pretrained segmentation model at image size 320:
        yolo predict model=yolov8n-seg.pt source='https://youtu.be/Zgi9g1ksQHc' imgsz=320

    3. Val a pretrained detection model at batch-size 1 and image size 640:
        yolo val model=yolov8n.pt data=coco128.yaml batch=1 imgsz=640

    4. Export a YOLOv8n classification model to ONNX format at image size 224 by 128 (no TASK required)
        yolo export model=yolov8n-cls.pt format=onnx imgsz=224,128

    5. Run special commands:
        yolo help
        yolo check
        yolo version
        yolo settings
        yolo copy-cfg
        yolo cfg

    Docs: https://docs.ultralytics.com
    Community: https://community.ultralytics.com
    GitHub: https://github.com/ultralytics/ultralytics我改成了0之后还在报错
